version: '3.8'

services:
  nextcloud:
    build: ./fm/nextcloud-api
    restart: always
    ports:
      - 8443:443
      - 8090:8090
    volumes:
      - nextcloud-data:/var/www/html
    env_file:
      - ./fm/env/local.env
    depends_on:
      - mariadb
  fm-app:
    build: ./fm/oar-fm-application-layer
    restart: always
    ports:
      - 9093:9093
    volumes:
      - nextcloud-data:/shared
      - fm-data:/fm
    env_file:
      - ./fm/env/local.env

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./fm/env/local.env

volumes:
  nextcloud-data:
  fm-data:
  db-data:
